//! 权限模型 v8 辅助模块：
//! - sudoers 白名单配置生成器（auth_mode='sudo' 的最小命令集）
//! - 命令参数校验工具（防注入：数字/域名/服务名/容器名等白名单匹配）

/// 生成 `/etc/sudoers.d/leepanel` 内容。
/// 用户以 auth_mode='sudo' 的账号执行时，仅放行以下固定命令集。
/// 部署方式：以 root 运行 `visudo -c -f <file>` 校验后复制到 /etc/sudoers.d/leepanel。
pub fn sudoers_config(username: &str) -> String {
    // 只读/查询类（各模块状态读取）
    let read_cmds = [
        "/usr/bin/systemctl status",
        "/usr/bin/systemctl list-units",
        "/usr/bin/docker ps",
        "/usr/bin/docker images",
        "/usr/bin/docker inspect",
        "/usr/bin/docker network ls",
        "/usr/bin/ss -tlnp",
        "/usr/bin/netstat -tlnp",
        "/usr/bin/ss -tnlp",
        "/usr/bin/netstat -tnlp",
        "/usr/bin/lsof",
        "/usr/bin/ps",
        "/usr/bin/df",
        "/usr/bin/free",
        "/usr/bin/uptime",
        "/usr/bin/cat",
        "/usr/bin/tail",
        "/usr/bin/nginx -t",
        "/usr/bin/php-fpm -t",
        "/usr/sbin/nginx -t",
        "/usr/sbin/php-fpm -t",
    ];
    // 管理/破坏性类（各模块写操作）
    let admin_cmds = [
        "/usr/bin/systemctl start",
        "/usr/bin/systemctl stop",
        "/usr/bin/systemctl restart",
        "/usr/bin/systemctl reload",
        "/usr/bin/systemctl enable",
        "/usr/bin/systemctl disable",
        "/usr/bin/docker start",
        "/usr/bin/docker stop",
        "/usr/bin/docker restart",
        "/usr/bin/docker rm",
        "/usr/bin/docker rmi",
        "/usr/bin/docker pull",
        "/usr/bin/docker build",
        "/usr/bin/docker network create",
        "/usr/bin/docker network rm",
        "/usr/bin/kill",
        "/usr/bin/pkill",
        "/usr/bin/reboot",
        "/usr/bin/ufw allow",
        "/usr/bin/ufw deny",
        "/usr/bin/ufw delete",
        "/usr/bin/firewall-cmd",
        "/usr/bin/iptables",
        "/usr/bin/nft",
    ];
    let mut out = String::new();
    out.push_str("# LeePanel sudo whitelist — generated by LeePanel\n");
    out.push_str("# Validate with: sudo visudo -c -f /tmp/leepanel\n");
    out.push_str("# Deploy with:   sudo install -m 440 -o root -g root /tmp/leepanel /etc/sudoers.d/leepanel\n");
    out.push_str(&format!("{} ALL=(root) NOPASSWD: ", username));
    let all: Vec<&str> = read_cmds.iter().chain(admin_cmds.iter()).copied().collect();
    out.push_str(&all.join(", "));
    out.push('\n');
    out
}

// ===== 参数校验（防注入） =====

fn reject(bad: &str, what: &str) -> Result<(), String> {
    Err(format!("Invalid {}: '{}'", what, bad))
}

/// 服务名：systemd unit 名（`[a-zA-Z0-9_.@-]+`，≤64 字符）。
pub fn validate_service_name(s: &str) -> Result<(), String> {
    if s.is_empty() || s.len() > 64 || !s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '@' | '-')) {
        return reject(s, "service name");
    }
    Ok(())
}

/// systemctl action：仅允许固定枚举。
pub fn validate_service_action(a: &str) -> Result<(), String> {
    if !matches!(a, "start" | "stop" | "restart" | "reload" | "enable" | "disable" | "status") {
        return reject(a, "service action");
    }
    Ok(())
}

/// 端口：1-65535。返回解析后的 u16。
pub fn validate_port(s: &str) -> Result<u16, String> {
    let p: u16 = s.trim().parse().map_err(|_| format!("Invalid port: '{}'", s))?;
    if p == 0 { return Err("Invalid port: must be 1-65535".to_string()); }
    Ok(p)
}

/// 协议：tcp/udp 枚举。
pub fn validate_protocol(s: &str) -> Result<(), String> {
    let l = s.to_ascii_lowercase();
    if l != "tcp" && l != "udp" { return reject(s, "protocol"); }
    Ok(())
}

/// PID：正整数。返回解析后的 u32。
pub fn validate_pid(s: &str) -> Result<u32, String> {
    let pid: u32 = s.trim().parse().map_err(|_| format!("Invalid PID: '{}'", s))?;
    if pid == 0 { return Err("Invalid PID: must be > 0".to_string()); }
    Ok(pid)
}

/// 域名 / 站点名：字母数字、点、短横线、下划线，≤253 字符，至少含一个点或可接受裸名。
pub fn validate_domain(s: &str) -> Result<(), String> {
    if s.is_empty() || s.len() > 253
        || !s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_'))
        || s.starts_with('.') || s.ends_with('.') {
        return reject(s, "domain");
    }
    Ok(())
}

/// Docker 容器/镜像名：`[a-zA-Z0-9][a-zA-Z0-9_.-]*`，≤128 字符。
pub fn validate_container_name(s: &str) -> Result<(), String> {
    if s.is_empty() || s.len() > 128
        || !s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | ':' | '/'))
        || s.starts_with('/') {
        return reject(s, "container/image name");
    }
    Ok(())
}

/// 远端路径：绝对路径、无控制字符、不含 `$()` `` ` `` `;` `&&` `||` `|` 等注入字符。
pub fn validate_path(s: &str) -> Result<(), String> {
    if s.is_empty() || !s.starts_with('/') {
        return reject(s, "path");
    }
    if s.chars().any(|c| c.is_control() || matches!(c, '$' | '`' | ';' | '&' | '|' | '<' | '>' | '\'' | '"' | '\n' | '\r')) {
        return reject(s, "path");
    }
    Ok(())
}

/// 软件包名（apt/dnf 包名）：`[a-z0-9][a-z0-9+.-]*`，≤128 字符。
pub fn validate_package_name(s: &str) -> Result<(), String> {
    if s.is_empty() || s.len() > 128
        || !s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '+' | '-' | '_')) {
        return reject(s, "package name");
    }
    Ok(())
}

/// 防火墙端口：单个端口或范围 `8080` / `8080:8090`，每段数值 1-65535。
pub fn validate_firewall_port(s: &str) -> Result<(), String> {
    let t = s.trim();
    if t.is_empty() || t.matches(':').count() > 1 {
        return reject(s, "firewall port");
    }
    for part in t.split(':') {
        let p: u16 = part.parse().map_err(|_| format!("Invalid firewall port: '{}'", s))?;
        if p == 0 { return Err("Invalid firewall port: must be 1-65535".to_string()); }
    }
    Ok(())
}

/// 防火墙协议：tcp/udp/both/any。
pub fn validate_firewall_protocol(s: &str) -> Result<(), String> {
    let l = s.to_ascii_lowercase();
    if !matches!(l.as_str(), "tcp" | "udp" | "both" | "any") {
        return reject(s, "firewall protocol");
    }
    Ok(())
}

/// 防火墙动作：allow/deny。
pub fn validate_firewall_action(s: &str) -> Result<(), String> {
    if s != "allow" && s != "deny" {
        return reject(s, "firewall action");
    }
    Ok(())
}

/// Docker 操作枚举：start/stop/restart。
pub fn validate_container_action(a: &str) -> Result<(), String> {
    if !matches!(a, "start" | "stop" | "restart") {
        return reject(a, "container action");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sudoers_config_includes_username() {
        let cfg = sudoers_config("admin");
        assert!(cfg.contains("admin ALL=(root) NOPASSWD:"));
        assert!(cfg.contains("/usr/bin/systemctl restart"));
        assert!(cfg.contains("/usr/bin/docker rm"));
        assert!(cfg.contains("/usr/bin/reboot"));
    }

    #[test]
    fn service_name_ok() {
        assert!(validate_service_name("nginx").is_ok());
        assert!(validate_service_name("php8.1-fpm").is_ok());
        assert!(validate_service_name("docker.service").is_ok());
        assert!(validate_service_name("").is_err());
        assert!(validate_service_name("nginx; rm -rf /").is_err());
        assert!(validate_service_name("a b").is_err());
    }

    #[test]
    fn service_action_ok() {
        assert!(validate_service_action("restart").is_ok());
        assert!(validate_service_action("START").is_err());
        assert!(validate_service_action("--all").is_err());
    }

    #[test]
    fn port_ok() {
        assert_eq!(validate_port("22").unwrap(), 22);
        assert_eq!(validate_port("65535").unwrap(), 65535);
        assert!(validate_port("0").is_err());
        assert!(validate_port("70000").is_err());
        assert!(validate_port("abc").is_err());
        assert!(validate_port("22; rm -rf /").is_err());
    }

    #[test]
    fn protocol_ok() {
        assert!(validate_protocol("tcp").is_ok());
        assert!(validate_protocol("UDP").is_ok());
        assert!(validate_protocol("icmp").is_err());
    }

    #[test]
    fn pid_ok() {
        assert_eq!(validate_pid("1234").unwrap(), 1234);
        assert!(validate_pid("0").is_err());
        assert!(validate_pid("-1").is_err());
        assert!(validate_pid("abc").is_err());
    }

    #[test]
    fn domain_ok() {
        assert!(validate_domain("example.com").is_ok());
        assert!(validate_domain("my_site.io").is_ok());
        assert!(validate_domain("example.com; rm -rf /").is_err());
        assert!(validate_domain(".example.com").is_err());
        assert!(validate_domain("").is_err());
    }

    #[test]
    fn container_name_ok() {
        assert!(validate_container_name("web").is_ok());
        assert!(validate_container_name("my_app:latest").is_ok());
        assert!(validate_container_name("reg.example.com/img:v1").is_ok());
        assert!(validate_container_name("web; rm -rf /").is_err());
        assert!(validate_container_name("/etc/passwd").is_err());
    }

    #[test]
    fn path_ok() {
        assert!(validate_path("/etc/nginx/nginx.conf").is_ok());
        assert!(validate_path("etc/nginx").is_err());
        assert!(validate_path("/tmp/a$(id).txt").is_err());
        assert!(validate_path("/tmp/a;b").is_err());
    }

    #[test]
    fn package_name_ok() {
        assert!(validate_package_name("nginx").is_ok());
        assert!(validate_package_name("libssl1.1").is_ok());
        assert!(validate_package_name("nginx; rm -rf /").is_err());
    }

    #[test]
    fn firewall_ok() {
        assert!(validate_firewall_port("8080").is_ok());
        assert!(validate_firewall_port("8080:8090").is_ok());
        assert!(validate_firewall_port("0").is_err());
        assert!(validate_firewall_port("70000").is_err());
        assert!(validate_firewall_port("8080; rm -rf /").is_err());
        assert!(validate_firewall_protocol("tcp").is_ok());
        assert!(validate_firewall_protocol("both").is_ok());
        assert!(validate_firewall_protocol("icmp").is_err());
        assert!(validate_firewall_action("allow").is_ok());
        assert!(validate_firewall_action("deny").is_ok());
        assert!(validate_firewall_action("ACCEPT").is_err());
    }

    #[test]
    fn container_action_ok() {
        assert!(validate_container_action("start").is_ok());
        assert!(validate_container_action("restart").is_ok());
        assert!(validate_container_action("rm -rf /").is_err());
    }
}
